// Centralized audio manifest. Every cue is placed on the master timeline in
// SECONDS; AsmrAudioLayer converts to frames at the active fps. Volumes are
// per-cue, then multiplied by family volume and master volume from CONFIG.
//
// All files are placeholder WAVs generated by scripts/generate-placeholder-audio.mjs
// (deterministic, no network). Replace with professional close-mic'd
// recordings using the same filenames — see public/assets/README.md.

export type AudioFamily =
  | 'ambience'
  | 'syrup'
  | 'pancake'
  | 'knife'
  | 'citrus'
  | 'ice'
  | 'liquid'
  | 'glass'
  | 'transitions';

export interface AudioCue {
  /** path under public/assets/audio */
  file: string;
  family: AudioFamily;
  /** start time on the master timeline, seconds */
  start: number;
  /** natural length of the file, seconds (for fade math) */
  dur: number;
  vol: number;
  fadeIn?: number;
  fadeOut?: number;
}

export const AUDIO_MANIFEST: AudioCue[] = [
  // ---- room tone: full length, loop-clean ends ----
  { file: 'ambience/room-tone.wav', family: 'ambience', start: 0, dur: 60, vol: 0.8, fadeIn: 0.2, fadeOut: 0.4 },

  // ---- Scene 1: hook (0–4) ----
  { file: 'pancake/plate-contact.wav', family: 'pancake', start: 0.4, dur: 0.8, vol: 0.7 },
  { file: 'syrup/glass-click.wav', family: 'syrup', start: 1.2, dur: 0.5, vol: 0.7 },
  { file: 'syrup/glass-click-2.wav', family: 'syrup', start: 2.1, dur: 0.5, vol: 0.6 },
  { file: 'syrup/glass-click.wav', family: 'syrup', start: 3.0, dur: 0.5, vol: 0.55 },
  { file: 'syrup/warm-crackle.wav', family: 'syrup', start: 0.6, dur: 3.4, vol: 0.45, fadeIn: 0.4, fadeOut: 0.5 },
  { file: 'syrup/bubble-close.wav', family: 'syrup', start: 3.4, dur: 0.7, vol: 0.85 },

  // ---- Scene 2: heating (4–14) ----
  { file: 'syrup/crystal-tick.wav', family: 'syrup', start: 4.6, dur: 0.4, vol: 0.6 },
  { file: 'syrup/crystal-tick.wav', family: 'syrup', start: 6.1, dur: 0.4, vol: 0.5 },
  { file: 'syrup/crystal-tick-2.wav', family: 'syrup', start: 7.7, dur: 0.4, vol: 0.6 },
  { file: 'syrup/crystal-tick.wav', family: 'syrup', start: 9.4, dur: 0.4, vol: 0.45 },
  { file: 'syrup/crystal-tick-2.wav', family: 'syrup', start: 11.2, dur: 0.4, vol: 0.5 },
  { file: 'syrup/stretch.wav', family: 'syrup', start: 8.4, dur: 1.6, vol: 0.75, fadeIn: 0.15 },
  { file: 'syrup/stretch.wav', family: 'syrup', start: 11.6, dur: 1.6, vol: 0.6, fadeIn: 0.15 },
  { file: 'syrup/bubble-pop.wav', family: 'syrup', start: 6.8, dur: 0.35, vol: 0.55 },
  { file: 'syrup/bubble-pop.wav', family: 'syrup', start: 10.2, dur: 0.35, vol: 0.5 },
  { file: 'syrup/bubble-pop.wav', family: 'syrup', start: 12.6, dur: 0.35, vol: 0.55 },
  { file: 'pancake/griddle-loop.wav', family: 'pancake', start: 4, dur: 10, vol: 0.3, fadeIn: 1, fadeOut: 1 },

  // ---- Scene 3: rainfall (14–27) ----
  { file: 'syrup/drip-heavy.wav', family: 'syrup', start: 14.6, dur: 0.9, vol: 0.95 },
  { file: 'pancake/compress.wav', family: 'pancake', start: 14.75, dur: 0.7, vol: 0.7 },
  { file: 'syrup/drip-mid.wav', family: 'syrup', start: 16.9, dur: 0.8, vol: 0.8 },
  { file: 'syrup/drip-mid-2.wav', family: 'syrup', start: 19.2, dur: 0.8, vol: 0.75 },
  { file: 'syrup/stretch.wav', family: 'syrup', start: 20.6, dur: 1.6, vol: 0.65 },
  { file: 'syrup/drip-light.wav', family: 'syrup', start: 21.8, dur: 0.7, vol: 0.7 },
  { file: 'syrup/drip-mid.wav', family: 'syrup', start: 23.2, dur: 0.8, vol: 0.7 },
  { file: 'syrup/fold.wav', family: 'syrup', start: 24.5, dur: 1.4, vol: 0.85, fadeIn: 0.1 },
  { file: 'syrup/drip-heavy.wav', family: 'syrup', start: 24.8, dur: 0.9, vol: 0.8 },
  { file: 'pancake/compress.wav', family: 'pancake', start: 25.0, dur: 0.7, vol: 0.6 },
  { file: 'syrup/drip-heavy.wav', family: 'syrup', start: 25.7, dur: 0.9, vol: 0.7 },
  { file: 'glass/plate-resonance.wav', family: 'glass', start: 25.95, dur: 1.6, vol: 0.55 },

  // ---- Scene 4: glaze (27–38) ----
  { file: 'knife/scrape-soft.wav', family: 'knife', start: 27.6, dur: 3.6, vol: 0.55, fadeIn: 0.4, fadeOut: 0.6 },
  { file: 'syrup/spread-sticky.wav', family: 'syrup', start: 28.2, dur: 3.0, vol: 0.8, fadeIn: 0.3, fadeOut: 0.4 },
  { file: 'syrup/spread-sticky.wav', family: 'syrup', start: 31.8, dur: 3.0, vol: 0.7, fadeIn: 0.3, fadeOut: 0.4 },
  { file: 'syrup/bubble-pop.wav', family: 'syrup', start: 30.4, dur: 0.35, vol: 0.45 },
  { file: 'syrup/bubble-pop.wav', family: 'syrup', start: 33.1, dur: 0.35, vol: 0.4 },
  { file: 'knife/utensil-ceramic.wav', family: 'knife', start: 33.6, dur: 0.6, vol: 0.65 },
  { file: 'ice/movement-faint.wav', family: 'ice', start: 35.4, dur: 2.6, vol: 0.4, fadeIn: 0.8 },
  { file: 'transitions/ripple-ring.wav', family: 'transitions', start: 36.6, dur: 1.8, vol: 0.7, fadeIn: 0.1, fadeOut: 0.5 },

  // ---- Scene 5: lemon reveal (38–42) ----
  { file: 'glass/glass-ring.wav', family: 'glass', start: 38.1, dur: 1.6, vol: 0.6, fadeOut: 0.5 },
  { file: 'liquid/condensation-drop.wav', family: 'liquid', start: 39.5, dur: 0.6, vol: 0.6 },
  { file: 'knife/board-touch.wav', family: 'knife', start: 40.5, dur: 0.5, vol: 0.6 },
  { file: 'knife/knife-place.wav', family: 'knife', start: 41.4, dur: 0.6, vol: 0.65 },

  // ---- Scene 6: knife cut (42–49) ----
  { file: 'knife/knife-contact.wav', family: 'knife', start: 42.6, dur: 0.5, vol: 0.9 },
  { file: 'citrus/peel-rupture.wav', family: 'citrus', start: 42.75, dur: 1.1, vol: 0.9 },
  { file: 'citrus/pulp-separate.wav', family: 'citrus', start: 43.5, dur: 1.3, vol: 0.85 },
  { file: 'knife/board-tap.wav', family: 'knife', start: 44.9, dur: 0.4, vol: 0.7 },
  { file: 'liquid/droplets-stone.wav', family: 'liquid', start: 45.4, dur: 0.7, vol: 0.6 },
  { file: 'liquid/droplets-stone.wav', family: 'liquid', start: 46.1, dur: 0.7, vol: 0.5 },

  // ---- Scene 7: lemonade (49–57) ----
  { file: 'citrus/squeeze.wav', family: 'citrus', start: 49.3, dur: 1.9, vol: 0.85, fadeIn: 0.1 },
  { file: 'liquid/stream-pour.wav', family: 'liquid', start: 51.2, dur: 3.8, vol: 0.9, fadeIn: 0.25, fadeOut: 0.5 },
  { file: 'ice/clink.wav', family: 'ice', start: 51.7, dur: 0.6, vol: 0.75 },
  { file: 'ice/clink-2.wav', family: 'ice', start: 52.5, dur: 0.6, vol: 0.65 },
  { file: 'ice/clink.wav', family: 'ice', start: 53.6, dur: 0.6, vol: 0.6 },
  { file: 'liquid/fizz-loop.wav', family: 'liquid', start: 52.0, dur: 8.0, vol: 0.5, fadeIn: 0.8, fadeOut: 1.2 },
  { file: 'glass/glass-resonance.wav', family: 'glass', start: 55.4, dur: 1.2, vol: 0.6 },
  { file: 'liquid/condensation-drop.wav', family: 'liquid', start: 56.2, dur: 0.6, vol: 0.5 },

  // ---- Scene 8: hero + loop (57–60) ----
  { file: 'syrup/drip-mid.wav', family: 'syrup', start: 57.6, dur: 0.8, vol: 0.6 },
  { file: 'ice/settle.wav', family: 'ice', start: 58.2, dur: 0.9, vol: 0.55 },
];

/** Unique list of every audio file the project expects (for QA checks). */
export const AUDIO_FILES = [...new Set(AUDIO_MANIFEST.map((c) => c.file))];
