"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { AgentAvatar } from "@/components/ui";
import { teamPlaybooks, integrations, type TeamPlaybook } from "@/lib/data";

type Stage = "ask" | "plan" | "building" | "done";

/** Matches a free-text business description to the closest team playbook. */
function matchPlaybook(text: string): TeamPlaybook {
  const t = text.toLowerCase();
  let best = teamPlaybooks[0];
  let bestScore = 0;
  for (const pb of teamPlaybooks) {
    const score = pb.keywords.reduce((n, k) => n + (t.includes(k) ? 1 : 0), 0);
    if (score > bestScore) {
      best = pb;
      bestScore = score;
    }
  }
  return best;
}

function integrationName(id: string) {
  return integrations.find((i) => i.id === id)?.name ?? id;
}

/**
 * The Emissary Assistant: describe your business (or pick a type) and it
 * assembles a pre-configured, pre-connected AI team. In production the plan
 * step is generated by the LLM layer from the description + the playbook
 * library; deployment creates real agents, connects OAuth scopes, and
 * schedules first runs.
 */
export function Assistant() {
  const [stage, setStage] = useState<Stage>("ask");
  const [text, setText] = useState("");
  const [playbook, setPlaybook] = useState<TeamPlaybook | null>(null);
  const [buildStep, setBuildStep] = useState(0);
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);

  useEffect(() => () => timers.current.forEach(clearTimeout), []);

  function propose(pb: TeamPlaybook) {
    setPlaybook(pb);
    setStage("plan");
  }

  function deploy() {
    if (!playbook) return;
    setStage("building");
    setBuildStep(0);
    const steps = buildSteps(playbook);
    steps.forEach((_, i) => {
      timers.current.push(setTimeout(() => setBuildStep(i + 1), 550 * (i + 1)));
    });
    timers.current.push(setTimeout(() => setStage("done"), 550 * (steps.length + 1) + 300));
  }

  function buildSteps(pb: TeamPlaybook): string[] {
    return [
      ...pb.integrations.map((i) => `Connecting ${integrationName(i)} (scoped access)`),
      ...pb.agents.map((a) => `Creating ${a.name} — ${a.role.toLowerCase()}`),
      "Applying approval guardrails to every agent",
      "Scheduling first runs",
    ];
  }

  /* ---------------------------------------------------------- ask */
  if (stage === "ask") {
    return (
      <div className="mx-auto max-w-2xl">
        <div className="rounded-2xl bg-gradient-to-br from-violet-600 to-ink-900 p-[1px] shadow-card-lg">
          <div className="rounded-2xl bg-white p-6 sm:p-8">
            <span className="inline-flex items-center gap-2 rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">
              <SparkIcon /> Emissary Assistant
            </span>
            <h1 className="mt-4 text-2xl font-semibold tracking-tight text-ink-950">
              Tell me about your business. I&rsquo;ll build your AI team.
            </h1>
            <p className="mt-2 text-sm leading-relaxed text-ink-500">
              Describe what your company does and what eats your team&rsquo;s time. I&rsquo;ll assemble
              pre-configured coworkers, connect the right apps, and schedule the first runs —
              with approval guardrails on from the start.
            </p>
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              rows={3}
              placeholder="e.g. We flip houses in Austin and San Antonio — finding deals fast is everything, and comping properties eats our afternoons."
              className="mt-5 w-full rounded-xl border border-ink-200 px-4 py-3 text-sm leading-relaxed text-ink-900 placeholder:text-ink-300 focus:border-violet-400 focus:outline-none focus:ring-2 focus:ring-violet-100"
            />
            <button
              onClick={() => text.trim() && propose(matchPlaybook(text))}
              disabled={!text.trim()}
              className="mt-4 w-full rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white shadow-[0_4px_14px_rgb(107_43_247/0.35)] transition hover:bg-violet-700 disabled:opacity-40 disabled:shadow-none"
            >
              Build my team
            </button>
          </div>
        </div>

        <p className="mt-8 text-center text-xs font-semibold uppercase tracking-widest text-ink-400">
          or start from a business type
        </p>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          {teamPlaybooks.map((pb) => (
            <button
              key={pb.id}
              onClick={() => propose(pb)}
              className="rounded-xl border border-ink-200 bg-white p-4 text-left shadow-card transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-card-lg"
            >
              <p className="text-sm font-semibold text-ink-950">{pb.business}</p>
              <p className="mt-1 text-xs leading-relaxed text-ink-500">{pb.headline}</p>
              <p className="mt-2 text-[11px] font-medium text-violet-600">
                {pb.agents.length} agents · {pb.integrations.length} integrations · ready in minutes
              </p>
            </button>
          ))}
        </div>
      </div>
    );
  }

  /* --------------------------------------------------------- plan */
  if (stage === "plan" && playbook) {
    return (
      <div className="mx-auto max-w-2xl">
        <button onClick={() => setStage("ask")} className="text-sm font-medium text-violet-600 hover:text-violet-800">
          ← Change business type
        </button>
        <div className="mt-4 rounded-2xl border border-ink-100 bg-white p-6 shadow-card sm:p-8">
          <span className="inline-flex items-center gap-2 rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">
            <SparkIcon /> Proposed team · {playbook.business}
          </span>
          <h1 className="mt-4 text-2xl font-semibold tracking-tight text-ink-950">{playbook.headline}</h1>
          <p className="mt-2 text-sm leading-relaxed text-ink-500">{playbook.summary}</p>

          <div className="mt-6 space-y-3">
            {playbook.agents.map((a) => (
              <div key={a.name} className="flex items-start gap-3 rounded-xl border border-ink-100 bg-ink-50/50 p-4">
                <AgentAvatar initials={a.initials} hue={a.hue} size="md" />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-baseline gap-x-2">
                    <p className="text-sm font-semibold text-ink-950">{a.name}</p>
                    <p className="text-xs text-ink-400">{a.role}</p>
                  </div>
                  <p className="mt-1 text-xs leading-relaxed text-ink-600">{a.brief}</p>
                  <p className="mt-1.5 text-[11px] text-ink-400">
                    {a.schedule} → {a.output}
                  </p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-5 rounded-xl bg-violet-50 p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-violet-700">Connects automatically</p>
            <div className="mt-2 flex flex-wrap gap-2">
              {playbook.integrations.map((i) => (
                <span key={i} className="rounded-lg bg-white px-3 py-1.5 text-xs font-medium text-ink-700 ring-1 ring-violet-100">
                  {integrationName(i)}
                </span>
              ))}
            </div>
            <p className="mt-3 text-xs leading-relaxed text-violet-900/70">
              First deliverable: {playbook.firstDeliverable}. Sensitive actions — messages, form
              submissions, CRM publishes — always pause for your approval.
            </p>
          </div>

          <button
            onClick={deploy}
            className="mt-6 w-full rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white shadow-[0_4px_14px_rgb(107_43_247/0.35)] transition hover:bg-violet-700"
          >
            Deploy this team
          </button>
        </div>
      </div>
    );
  }

  /* ----------------------------------------------------- building */
  if (stage === "building" && playbook) {
    const steps = buildSteps(playbook);
    return (
      <div className="mx-auto max-w-md pt-8">
        <div className="rounded-2xl border border-ink-100 bg-white p-6 shadow-card sm:p-8">
          <p className="text-sm font-semibold text-ink-950">Deploying your team…</p>
          <ul className="mt-5 space-y-3">
            {steps.map((s, i) => (
              <li key={s} className="flex items-center gap-3 text-sm">
                {i < buildStep ? (
                  <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-emerald-600">
                    <svg viewBox="0 0 12 12" className="h-3 w-3" fill="none"><path d="M2.5 6.5l2.5 2.5 4.5-5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>
                  </span>
                ) : i === buildStep ? (
                  <span className="h-5 w-5 shrink-0 animate-spin rounded-full border-2 border-violet-200 border-t-violet-600" />
                ) : (
                  <span className="h-5 w-5 shrink-0 rounded-full border-2 border-ink-100" />
                )}
                <span className={i <= buildStep ? "text-ink-800" : "text-ink-300"}>{s}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    );
  }

  /* --------------------------------------------------------- done */
  if (stage === "done" && playbook) {
    return (
      <div className="mx-auto max-w-2xl pt-4 text-center">
        <span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600">
          <svg viewBox="0 0 24 24" fill="none" className="h-8 w-8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12.5l4.5 4.5L19 7.5" /></svg>
        </span>
        <h1 className="mt-5 text-2xl font-semibold tracking-tight text-ink-950">Your AI team is on the clock</h1>
        <p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-ink-500">
          {playbook.agents.length} coworkers deployed, {playbook.integrations.length} integrations
          connected, first runs scheduled. {playbook.firstDeliverable}.
        </p>
        <div className="mt-7 space-y-3 text-left">
          {playbook.agents.map((a) => (
            <div key={a.name} className="flex items-center gap-3 rounded-xl border border-ink-100 bg-white p-4 shadow-card">
              <AgentAvatar initials={a.initials} hue={a.hue} size="md" />
              <div className="min-w-0 flex-1">
                <p className="text-sm font-semibold text-ink-950">{a.name}</p>
                <p className="truncate text-xs text-ink-400">{a.schedule} → {a.output}</p>
              </div>
              <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700">
                <span className="h-1.5 w-1.5 animate-pulse-dot rounded-full bg-emerald-500" />
                Working
              </span>
            </div>
          ))}
        </div>
        <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
          <Link href="/dashboard/agents" className="rounded-xl bg-violet-600 px-6 py-3 text-sm font-semibold text-white shadow-[0_4px_14px_rgb(107_43_247/0.35)] transition hover:bg-violet-700">
            Watch them work
          </Link>
          <button
            onClick={() => { setStage("ask"); setText(""); setPlaybook(null); }}
            className="rounded-xl border border-ink-200 bg-white px-6 py-3 text-sm font-medium text-ink-700 transition hover:bg-ink-50"
          >
            Build another team
          </button>
        </div>
      </div>
    );
  }

  return null;
}

function SparkIcon() {
  return (
    <svg viewBox="0 0 16 16" className="h-3.5 w-3.5" fill="currentColor" aria-hidden="true">
      <path d="M8 1.5l1.4 3.6a2 2 0 001.5 1.5L14.5 8l-3.6 1.4a2 2 0 00-1.5 1.5L8 14.5 6.6 10.9a2 2 0 00-1.5-1.5L1.5 8l3.6-1.4a2 2 0 001.5-1.5L8 1.5z" />
    </svg>
  );
}
